import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { searchMerchants, addMerchant, updateMerchant } from '../services/merchantService';
import { Merchant, SearchRequestPayload, MerchantSearchResponse, MerchantAddPayload, MerchantEditPayload, FormErrors } from '../types/merchant';
import { Toast } from '../components/common/Toast';
import { ConfirmDialog } from '../components/common/ConfirmDialog';
import './Merchants.css';

/**
 * Merchants Page Component
 * 
 * Displays a searchable, paginated list of merchants using the POST /merchants/search API
 * Includes merchant creation and edit forms with validation
 */
export const Merchants = () => {
  const navigate = useNavigate();

  // List state
  const [merchants, setMerchants] = useState<Merchant[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [currentPage, setCurrentPage] = useState<number>(0);
  const [pageSize, setPageSize] = useState<number>(10);
  const [totalPages, setTotalPages] = useState<number>(0);
  const [totalRecords, setTotalRecords] = useState<number>(0);
  const [sortField, setSortField] = useState<string>('name');
  const [sortOrder, setSortOrder] = useState<string>('asc');

  // Form state
  const [showForm, setShowForm] = useState<boolean>(false);
  const [formLoading, setFormLoading] = useState<boolean>(false);
  const [formErrors, setFormErrors] = useState<FormErrors>({});
  const [editMode, setEditMode] = useState<boolean>(false);
  const [editingMerchant, setEditingMerchant] = useState<Merchant | null>(null);
  
  // Toast state
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' | 'info' } | null>(null);
  
  // Confirmation dialog state
  const [showConfirm, setShowConfirm] = useState<boolean>(false);
  const [pendingFormData, setPendingFormData] = useState<MerchantAddPayload | MerchantEditPayload | null>(null);
  
  const [formData, setFormData] = useState<MerchantAddPayload>({
    id: '', // Will be auto-generated by backend
    name: '',
    email: '',
    phone: '',
    status: 'active',
    address: '',
    businessName: '',
  });

  // Fetch merchants from API
  const fetchMerchants = async () => {
    setLoading(true);
    
    const searchParams: SearchRequestPayload = {
      pageNumber: currentPage,
      pageSize: pageSize,
      sortField: sortField,
      sortOrder: sortOrder,
      searchParameter: searchQuery,
    };

    try {
      const response: MerchantSearchResponse = await searchMerchants(searchParams);
      setMerchants(response.data);
      setTotalPages(response.totalPage);
      setTotalRecords(response.totalRecord);
    } catch (err) {
      setToast({
        message: err instanceof Error ? err.message : 'Failed to fetch merchants',
        type: 'error'
      });
      setMerchants([]);
    } finally {
      setLoading(false);
    }
  };

  // Fetch merchants on initial load and when search parameters change
  useEffect(() => {
    fetchMerchants();
  }, [currentPage, pageSize, sortField, sortOrder]);

  // Handle search button click
  const handleSearch = () => {
    setCurrentPage(0); // Reset to first page
    fetchMerchants();
  };

  // Handle sort change
  const handleSort = (field: string) => {
    if (sortField === field) {
      setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortOrder('asc');
    }
  };

  // Handle edit button click
  const handleEdit = (merchant: Merchant) => {
    setEditMode(true);
    setEditingMerchant(merchant);
    setFormData({
      id: merchant.id,
      name: merchant.name,
      email: merchant.email,
      phone: merchant.phone,
      status: merchant.status,
      address: merchant.address || '',
      businessName: merchant.businessName || '',
    });
    setShowForm(true);
    setFormErrors({});
  };

  // Handle add button click
  const handleAddClick = () => {
    setEditMode(false);
    setEditingMerchant(null);
    setFormData({
      id: '',
      name: '',
      email: '',
      phone: '',
      status: 'active',
      address: '',
      businessName: '',
    });
    setShowForm(true);
    setFormErrors({});
  };

  // Handle cancel
  const handleCancel = () => {
    setShowForm(false);
    setEditMode(false);
    setEditingMerchant(null);
    setFormErrors({});
  };

  // Form validation
  const validateForm = (): boolean => {
    const errors: FormErrors = {};

    if (!formData.name.trim()) {
      errors.name = 'Name is required';
    }

    if (!formData.email.trim()) {
      errors.email = 'Email is required';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      errors.email = 'Invalid email format';
    }

    if (!formData.phone.trim()) {
      errors.phone = 'Phone is required';
    } else if (!/^\+?[\d\s-()]+$/.test(formData.phone)) {
      errors.phone = 'Invalid phone format';
    }

    if (!formData.businessName.trim()) {
      errors.businessName = 'Business name is required';
    }

    if (!formData.address.trim()) {
      errors.address = 'Address is required';
    }

    setFormErrors(errors);
    return Object.keys(errors).length === 0;
  };

  // Handle form input change
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    // Clear error for this field
    if (formErrors[name]) {
      setFormErrors(prev => ({ ...prev, [name]: '' }));
    }
  };

  // Handle form submit (show confirmation dialog)
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateForm()) {
      return;
    }

    // Store form data and show confirmation dialog
    setPendingFormData(formData);
    setShowConfirm(true);
  };

  // Handle confirmed submission
  const handleConfirmedSubmit = async () => {
    setShowConfirm(false);
    
    if (!pendingFormData) return;

    setFormLoading(true);

    try {
      if (editMode && editingMerchant) {
        // Update existing merchant
        await updateMerchant(pendingFormData as MerchantEditPayload);
        
        setToast({
          message: 'Merchant updated successfully!',
          type: 'success'
        });
      } else {
        // Add new merchant
        await addMerchant(pendingFormData as MerchantAddPayload);
        
        setToast({
          message: 'Merchant added successfully!',
          type: 'success'
        });
      }
      
      // Reset form
      setFormData({
        id: '',
        name: '',
        email: '',
        phone: '',
        status: 'active',
        address: '',
        businessName: '',
      });
      setFormErrors({});
      setShowForm(false);
      setEditMode(false);
      setEditingMerchant(null);
      setPendingFormData(null);
      
      // Refresh merchant list
      fetchMerchants();
    } catch (err) {
      setToast({
        message: err instanceof Error ? err.message : `Failed to ${editMode ? 'update' : 'add'} merchant`,
        type: 'error'
      });
    } finally {
      setFormLoading(false);
    }
  };

  return (
    <main className="container">
      {/* Toast Notification */}
      {toast && (
        <Toast
          message={toast.message}
          type={toast.type}
          onClose={() => setToast(null)}
        />
      )}

      {/* Confirmation Dialog */}
      {showConfirm && (
        <ConfirmDialog
          title={editMode ? 'Confirm Update' : 'Confirm Add Merchant'}
          message={editMode 
            ? `Are you sure you want to update ${editingMerchant?.name}?` 
            : 'Are you sure you want to add this merchant?'}
          confirmText={editMode ? 'Update' : 'Add'}
          cancelText="Cancel"
          onConfirm={handleConfirmedSubmit}
          onCancel={() => {
            setShowConfirm(false);
            setPendingFormData(null);
          }}
          type={editMode ? 'warning' : 'info'}
        />
      )}

      <div className="merchants-page">
        <div className="page-header">
          <div>
            <h1>🏢 Merchants Management</h1>
            <p className="subtitle">Manage merchant accounts and settings</p>
          </div>
          <button 
            className="btn-primary add-merchant-btn" 
            onClick={() => showForm ? handleCancel() : handleAddClick()}
            disabled={loading}
          >
            {showForm ? '✕ Cancel' : '+ Add Merchant'}
          </button>
        </div>

        {/* Add/Edit Merchant Form */}
        {showForm && (
          <div className="merchant-form-container">
            <h2>{editMode ? 'Edit Merchant' : 'Add New Merchant'}</h2>
            <form onSubmit={handleSubmit} className="merchant-form">
              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="status">Status *</label>
                  <select
                    id="status"
                    name="status"
                    value={formData.status}
                    onChange={handleInputChange}
                    disabled={formLoading}
                  >
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                    <option value="pending">Pending</option>
                  </select>
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="name">Contact Name *</label>
                  <input
                    type="text"
                    id="name"
                    name="name"
                    value={formData.name}
                    onChange={handleInputChange}
                    placeholder="John Doe"
                    disabled={formLoading}
                  />
                  {formErrors.name && <span className="error-text">{formErrors.name}</span>}
                </div>

                <div className="form-group">
                  <label htmlFor="businessName">Business Name *</label>
                  <input
                    type="text"
                    id="businessName"
                    name="businessName"
                    value={formData.businessName}
                    onChange={handleInputChange}
                    placeholder="Acme Corp"
                    disabled={formLoading}
                  />
                  {formErrors.businessName && <span className="error-text">{formErrors.businessName}</span>}
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label htmlFor="email">Email *</label>
                  <input
                    type="email"
                    id="email"
                    name="email"
                    value={formData.email}
                    onChange={handleInputChange}
                    placeholder="merchant@example.com"
                    disabled={formLoading}
                  />
                  {formErrors.email && <span className="error-text">{formErrors.email}</span>}
                </div>

                <div className="form-group">
                  <label htmlFor="phone">Phone *</label>
                  <input
                    type="tel"
                    id="phone"
                    name="phone"
                    value={formData.phone}
                    onChange={handleInputChange}
                    placeholder="+1 234 567 8900"
                    disabled={formLoading}
                  />
                  {formErrors.phone && <span className="error-text">{formErrors.phone}</span>}
                </div>
              </div>

              <div className="form-group">
                <label htmlFor="address">Address *</label>
                <textarea
                  id="address"
                  name="address"
                  value={formData.address}
                  onChange={handleInputChange}
                  placeholder="123 Main St, City, Country"
                  rows={3}
                  disabled={formLoading}
                />
                {formErrors.address && <span className="error-text">{formErrors.address}</span>}
              </div>

              <div className="form-actions">
                <button 
                  type="button" 
                  className="btn-secondary" 
                  onClick={handleCancel}
                  disabled={formLoading}
                >
                  Cancel
                </button>
                <button 
                  type="submit" 
                  className="btn-primary" 
                  disabled={formLoading}
                >
                  {formLoading ? (editMode ? 'Updating...' : 'Adding...') : (editMode ? 'Update Merchant' : 'Add Merchant')}
                </button>
              </div>
            </form>
          </div>
        )}

        {/* Search and Filter Section */}
        <div className="search-section">
          <div className="search-bar">
            <input
              type="text"
              placeholder="Search merchants by name, email, or ID..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              onKeyPress={(e) => e.key === 'Enter' && handleSearch()}
            />
            <button onClick={handleSearch} disabled={loading}>
              {loading ? 'Searching...' : '🔍 Search'}
            </button>
          </div>
          
          <div className="filter-controls">
            <label>
              Page Size:
              <select value={pageSize} onChange={(e) => setPageSize(Number(e.target.value))}>
                <option value={5}>5</option>
                <option value={10}>10</option>
                <option value={20}>20</option>
                <option value={50}>50</option>
              </select>
            </label>
          </div>
        </div>

        {/* Merchants Table */}
        {loading && merchants.length === 0 ? (
          <div className="loading-state">
            <div className="spinner"></div>
            <p>Loading merchants...</p>
          </div>
        ) : (
          <>
            <div className="table-container">
              <table className="merchants-table">
                <thead>
                  <tr>
                    <th onClick={() => handleSort('id')} className="sortable">
                      ID {sortField === 'id' && (sortOrder === 'asc' ? '↑' : '↓')}
                    </th>
                    <th onClick={() => handleSort('name')} className="sortable">
                      Name {sortField === 'name' && (sortOrder === 'asc' ? '↑' : '↓')}
                    </th>
                    <th>Business Name</th>
                    <th onClick={() => handleSort('email')} className="sortable">
                      Email {sortField === 'email' && (sortOrder === 'asc' ? '↑' : '↓')}
                    </th>
                    <th>Phone</th>
                    <th onClick={() => handleSort('status')} className="sortable">
                      Status {sortField === 'status' && (sortOrder === 'asc' ? '↑' : '↓')}
                    </th>
                    <th>Address</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {merchants.length === 0 ? (
                    <tr>
                      <td colSpan={8} className="empty-state">
                        No merchants found. Try adjusting your search criteria.
                      </td>
                    </tr>
                  ) : (
                    merchants.map((merchant) => (
                      <tr key={merchant.id}>
                        <td className="merchant-id">{merchant.id}</td>
                        <td className="merchant-name">{merchant.name}</td>
                        <td>{merchant.businessName || '-'}</td>
                        <td>{merchant.email}</td>
                        <td>{merchant.phone}</td>
                        <td>
                          <span className={`status-badge status-${merchant.status?.toLowerCase()}`}>
                            {merchant.status}
                          </span>
                        </td>
                        <td className="merchant-address">{merchant.address || '-'}</td>
                        <td>
                          <div className="action-buttons">
                            <button
                              className="btn-view"
                              onClick={() => navigate(`/merchants/${merchant.id}`)}
                              disabled={loading}
                            >
                              👁️ View
                            </button>
                            <button
                              className="btn-edit"
                              onClick={() => handleEdit(merchant)}
                              disabled={loading}
                            >
                              ✏️ Edit
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            {/* Pagination */}
            {totalRecords > 0 && (
              <div className="pagination">
                <div className="pagination-info">
                  Showing {currentPage * pageSize + 1} to {Math.min((currentPage + 1) * pageSize, totalRecords)} of {totalRecords} merchants
                </div>
                <div className="pagination-controls">
                  <button
                    onClick={() => setCurrentPage(0)}
                    disabled={currentPage === 0 || loading}
                  >
                    « First
                  </button>
                  <button
                    onClick={() => setCurrentPage(currentPage - 1)}
                    disabled={currentPage === 0 || loading}
                  >
                    ‹ Previous
                  </button>
                  <span className="page-number">
                    Page {currentPage + 1} of {totalPages}
                  </span>
                  <button
                    onClick={() => setCurrentPage(currentPage + 1)}
                    disabled={currentPage >= totalPages - 1 || loading}
                  >
                    Next ›
                  </button>
                  <button
                    onClick={() => setCurrentPage(totalPages - 1)}
                    disabled={currentPage >= totalPages - 1 || loading}
                  >
                    Last »
                  </button>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </main>
  );
};
